apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortiz-app
  template:
    metadata:
      labels:
        app: mortiz-app
    spec:
      containers:
        - name: mortiz-app
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
