apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortiz-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortiz-app
  template:
    metadata:
      labels:
        app: mortiz-app
    spec:
      containers:
        - name: mortiz-app
          image: nginx:latest
          ports:
            - containerPort: 8080
