apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mortiz
  template:
    metadata:
      labels:
        app: mortiz
    spec:
      containers:
        - name: mortiz-app2
          image: wil42/playground:v2
          ports:
            - containerPort: 8888
