apiVersion: v1
kind: Service
metadata:
  name: mortiz-app-service
  namespace: dev
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  type: LoadBalancer
  selector:
    app: mortiz-app