apiVersion: v1
kind: Service
metadata:
  name: mortiz-app-service
  namespace: dev
spec:
  selector:
    app: mortiz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
